### ISSUE TITLE
entity(domain) class의 제약조건의 추가가 필요합니다.

### ISSUE THREAD

**Issue by siwony** [themoment-team/K2-server#154]
현제 저희 Entity는 모두 제약조건이 정의되어있지 않습니다. 데이터 무결성을 유지하려면 제약조건을 추가해야 할것같습니다.

**Comment by Johnjihwan** [comment]
네 Entity 맡은 부분 testcode 작성하면서 추가하는걸로 하죠.
개인이 맡은 부분만 제약조건 추가 하는걸로 합시다 안그러면 conflict 문제가 생길 수 있으니깐요

**Comment by siwony** [comment]
네 알겠습니다. :)
