### ISSUE TITLE
Prod-Build 가 참조가 안되서 빌드가 안됨

### ISSUE THREAD

**Issue by codnstj** [themoment-team/K2-server#279]
Prod-Build 관련한 워크 플로우 수정해서 PR 날리도록 하겠습니다.

Prod-Build.sh 라는 파일이 없는데 cp 하려고 해서 그런것 같네요

**Comment by jyeonjyan** [comment]
네 그 `prod-build.sh` 는 backend 에서 docker로 테스트하기 위함으로 만들어둔거였고
DevOps 챕터에서 사용하지 않는다고 하셔서 삭제했어요. #276 

이슈 hotfix 해서 develop으로 PR 보내주세요.
